### ISSUE TITLE
内存占用比较高

### ISSUE THREAD

**Issue by wangzhaode** [youkaichao/fast_bpe_tokenizer#1]
这个实现非常简洁；但是内存占用比较高

**Comment by youkaichao** [comment]
是的，这个实现只是为了个人学习使用的。

**Comment by wangzhaode** [comment]
嗯嗯 感谢这个项目 之前mnn-llm中tiktoken部分使用的这个实现；今天在iPhone 11上测试时因为内存限制导致加载不了qwen的词表，所以提了下；现在我自己实现了一个性能不太好但是内存占用低的版本。

**Comment by youkaichao** [comment]
居然真的使用了吗，我都没料到有人会用它 👀

**Comment by youkaichao** [comment]
我看你用了dict来存储，太浪费了。我用的trie树，比dict应该高效很多。

**Comment by youkaichao** [comment]
另外，用了的话代码里可以致谢一下（加个链接）。

**Comment by wangzhaode** [comment]
使用的代码里有链接的:
https://github.com/wangzhaode/mnn-llm/blob/ccc14611524687282346073c773368e08482ca30/src/tokenizer.cpp#L347

**Comment by youkaichao** [comment]
我看master的code里没有诶，这是哪个commit

**Comment by youkaichao** [comment]
目前我是在每个节点都分配了256个子节点，所以内存占用会很大。稍微优化一下，可以只存储必要的子节点（比如用一个vector来存储子节点），这样可以大大减少内存占用。

trie树肯定能比dict快/省空间，只不过我的trie树实现得非常粗糙 👀

**Comment by wangzhaode** [comment]
> 我看master的code里没有诶，这是哪个commit

因为要在端侧运行，内存更加敏感；所以master中重写了，直接用map加循环实现了
